DATASET: 'globalscale'

# IN1k + MAE only
NO_SAM: False

BACKBONE: 'resnet'
USE_SKIP_CONNECTIONS: False
USE_CBAM: False
PATCH_SIZE: 512
BATCH_SIZE: 16
DATA_WORKER_NUM: 8
TRAIN_EPOCHS: 150
BASE_LR: 0.001
FREEZE_ENCODER: False
ENCODER_LR_FACTOR: 0.1
ENCODER_LORA: False
FOCAL_LOSS: False
USE_SAM_DECODER: False

# TOPONET
# sample per patch
TOPO_SAMPLE_NUM: 512
TOPONET_VERSION: 'normal'

# Inference
INFER_BATCH_SIZE: 32
SAMPLE_MARGIN: 64
INFER_PATCHES_PER_EDGE: 16

# Thresholds (to be determined after training)
# ======= keypoint ======
# Best threshold 0.07070706784725189, P=0.11688089370727539 
# R=0.1889704316854477 F1=0.14442986249923706
# ======= road ======
# Best threshold 0.23232322931289673, P=0.40067312121391296 
# R=0.5707035660743713 F1=0.4708072245121002
# ======= topo ======
# Best threshold 0.46464645862579346, P=0.9727776050567627 
# R=0.9686310887336731 F1=0.9706999659538269

ITSC_THRESHOLD: 0.070707
ROAD_THRESHOLD: 0.232323
TOPO_THRESHOLD: 0.464646
# pixels
ITSC_NMS_RADIUS: 8
ROAD_NMS_RADIUS: 16
NEIGHBOR_RADIUS: 64
MAX_NEIGHBOR_QUERIES: 16
