DATASET: 'cityscale'

# IN1k + MAE only
NO_SAM: False

SAM_VERSION: 'vit_b'
SAM_CKPT_PATH: 'sam_ckpts/sam_vit_b_01ec64.pth'
USE_SKIP_CONNECTIONS: False
USE_CBAM: False
PATCH_SIZE: 512
BATCH_SIZE: 16
DATA_WORKER_NUM: 8
TRAIN_EPOCHS: 150
BASE_LR: 0.001
FREEZE_ENCODER: False
ENCODER_LR_FACTOR: 0.1
ENCODER_LORA: False
FOCAL_LOSS: False
USE_SAM_DECODER: False

# TOPONET
# sample per patch
TOPO_SAMPLE_NUM: 512
TOPONET_VERSION: 'normal'

# Inference
INFER_BATCH_SIZE: 32
SAMPLE_MARGIN: 64
INFER_PATCHES_PER_EDGE: 16

# ======= keypoint ======
# Best threshold 0.21212121844291687, P=0.43389585614204407 R=0.3846842646598816 F1=0.4078108072280884
# ======= road ======
# Best threshold 0.3636363744735718, P=0.6908066272735596 R=0.7462158203125 F1=0.7174429893493652
# ======= topo ======
# Best threshold 0.4545454680919647, P=0.9748905301094055 R=0.9706118702888489 F1=0.9727464914321899

ITSC_THRESHOLD: 0.2121
ROAD_THRESHOLD: 0.3636
TOPO_THRESHOLD: 0.4545
# pixels
ITSC_NMS_RADIUS: 8
ROAD_NMS_RADIUS: 16
NEIGHBOR_RADIUS: 64
MAX_NEIGHBOR_QUERIES: 16