DATASET: 'cityscale'

# IN1k + MAE only
NO_SAM: False

BACKBONE: 'dinov2'
BACKBONE_CKPT_PATH: 'dino_ckpts/dinov2_vitb14_reg4_pretrain.pth'
USE_SKIP_CONNECTIONS: False
USE_CBAM: False
PATCH_SIZE: 512
BATCH_SIZE: 16
DATA_WORKER_NUM: 8
TRAIN_EPOCHS: 150
BASE_LR: 0.001
FREEZE_ENCODER: False
ENCODER_LR_FACTOR: 0.1
ENCODER_LORA: False
FOCAL_LOSS: False
USE_SAM_DECODER: False

# TOPONET
# sample per patch
TOPO_SAMPLE_NUM: 512
TOPONET_VERSION: 'normal'

# Inference
INFER_BATCH_SIZE: 32
SAMPLE_MARGIN: 64
INFER_PATCHES_PER_EDGE: 16

# ======= keypoint ======
# Best threshold 0.17171716690063477, P=0.3856319189071655 R=0.3476887047290802 F1=0.36567869782447815
# ======= road ======
# Best threshold 0.35353535413742065, P=0.6661077737808228 R=0.7371445298194885 F1=0.6998280882835388
# ======= topo ======
# Best threshold 0.4545454680919647, P=0.9727751016616821 R=0.9707914590835571 F1=0.9717822670936584

# Thresholds (to be determined after training)
ITSC_THRESHOLD: 0.1717
ROAD_THRESHOLD: 0.3535
TOPO_THRESHOLD: 0.4545
# pixels
ITSC_NMS_RADIUS: 8
ROAD_NMS_RADIUS: 16
NEIGHBOR_RADIUS: 64
MAX_NEIGHBOR_QUERIES: 16
