DATASET: "globalscale"
MODEL_TYPE: "gte"
BACKBONE: "dinov3"
NO_VFM: False
SAM_VERSION: "vit_b"
PATCH_SIZE: 512
BATCH_SIZE: 16
DATA_WORKER_NUM: 8
TRAIN_EPOCHS: 250
BASE_LR: 0.001
FREEZE_ENCODER: False
ENCODER_LR_FACTOR: 0.1
ENCODER_LORA: False
GTE_DECODER_VERSION: "v1"
INFER_BATCH_SIZE: 32
SAMPLE_MARGIN: 64
INFER_PATCHES_PER_EDGE: 16
