DATASET: 'globalscale'

# IN1k + MAE only
NO_SAM: False

BACKBONE: 'dinov2'
BACKBONE_CKPT_PATH: 'dino_ckpts/dinov2_vitb14_reg4_pretrain.pth'
USE_SKIP_CONNECTIONS: False
USE_CBAM: False
PATCH_SIZE: 512
BATCH_SIZE: 16
DATA_WORKER_NUM: 8
TRAIN_EPOCHS: 150
BASE_LR: 0.001
FREEZE_ENCODER: False
ENCODER_LR_FACTOR: 0.1
ENCODER_LORA: False
FOCAL_LOSS: False
USE_SAM_DECODER: False

# TOPONET
# sample per patch
TOPO_SAMPLE_NUM: 512
TOPONET_VERSION: 'normal'

# Inference
INFER_BATCH_SIZE: 32
SAMPLE_MARGIN: 64
INFER_PATCHES_PER_EDGE: 16

# Thresholds (to be determined after training)
# ======= keypoint ======
# Best threshold 0.12121212482452393, P=0.19844843447208405 
# R=0.2436026781797409 F1=0.21871937811374664
# ======= road ======
# Best threshold 0.2929292917251587, P=0.49345535039901733 
# R=0.6378191113471985 F1=0.5564259886741638
# ======= topo ======
# Best threshold 0.4545454680919647, P=0.9769406914710999 
# R=0.9732826352119446 F1=0.9751082062721252

ITSC_THRESHOLD: 0.121212
ROAD_THRESHOLD: 0.292929
TOPO_THRESHOLD: 0.454545
# pixels
ITSC_NMS_RADIUS: 8
ROAD_NMS_RADIUS: 16
NEIGHBOR_RADIUS: 64
MAX_NEIGHBOR_QUERIES: 16
