DATASET: 'globalscale'

# IN1k + MAE only
NO_SAM: False

SAM_VERSION: 'vit_b'
SAM_CKPT_PATH: 'sam_ckpts/sam_vit_b_01ec64.pth'
USE_SKIP_CONNECTIONS: False
USE_CBAM: False
PATCH_SIZE: 512
BATCH_SIZE: 16
DATA_WORKER_NUM: 8
TRAIN_EPOCHS: 150
BASE_LR: 0.001
FREEZE_ENCODER: False
ENCODER_LR_FACTOR: 0.1
ENCODER_LORA: False
FOCAL_LOSS: False
USE_SAM_DECODER: False

# TOPONET
# sample per patch
TOPO_SAMPLE_NUM: 512
TOPONET_VERSION: 'normal'

# Inference
INFER_BATCH_SIZE: 32
SAMPLE_MARGIN: 64
INFER_PATCHES_PER_EDGE: 16

# ======= keypoint ======
# Best threshold 0.14141413569450378, P=0.22881823778152466 R=0.2835550308227539 F1=0.25326287746429443
# ======= road ======
# Best threshold 0.3030303120613098, P=0.5108893513679504 R=0.6515319347381592 F1=0.5727024674415588
# ======= topo ======
# Best threshold 0.4444444477558136, P=0.9760676026344299 R=0.973872184753418 F1=0.974968671798706

ITSC_THRESHOLD: 0.141
ROAD_THRESHOLD: 0.303
TOPO_THRESHOLD: 0.444
# pixels
ITSC_NMS_RADIUS: 8
ROAD_NMS_RADIUS: 16
NEIGHBOR_RADIUS: 64
MAX_NEIGHBOR_QUERIES: 16