DATASET: 'globalscale_outdomain'

# IN1k + MAE only
NO_SAM: False

SAM_VERSION: 'sam2_hiera_b+'
SAM_CKPT_PATH: 'sam_ckpts/sam2.1_hiera_base_plus.pt'

# Vanilla SAM2 (No FPN, No CBAM, No HD Topo)
USE_SKIP_CONNECTIONS: False
USE_CBAM: False
USE_HIGH_RES_TOPO: False

PATCH_SIZE: 512
BATCH_SIZE: 16
DATA_WORKER_NUM: 8
TRAIN_EPOCHS: 150
BASE_LR: 0.001
FREEZE_ENCODER: False
ENCODER_LR_FACTOR: 0.1
ENCODER_LORA: False
FOCAL_LOSS: False
USE_SAM_DECODER: False

# TOPONET
# sample per patch
TOPO_SAMPLE_NUM: 512
TOPONET_VERSION: 'normal'

# Inference
INFER_BATCH_SIZE: 32
SAMPLE_MARGIN: 64
INFER_PATCHES_PER_EDGE: 16

# ======= keypoint ======
# Best threshold 0.13131313025951385, P=0.24271471798419952 R=0.290793776512146 F1=0.2645878493785858
# ======= road ======
# Best threshold 0.3030303120613098, P=0.5261251330375671 R=0.6523586511611938 F1=0.5824811458587646
# ======= topo ======
# Best threshold 0.4343434274196625, P=0.9769645929336548 R=0.9747323393821716 F1=0.9758471846580505

ITSC_THRESHOLD: 0.1313
ROAD_THRESHOLD: 0.3030
TOPO_THRESHOLD: 0.4343
# pixels
ITSC_NMS_RADIUS: 8
ROAD_NMS_RADIUS: 16
NEIGHBOR_RADIUS: 64
MAX_NEIGHBOR_QUERIES: 16
