DATASET: 'globalscale_outdomain'

# IN1k + MAE only
NO_SAM: False

SAM_VERSION: 'radio'
BACKBONE: 'radio'
BACKBONE_NAME: 'nvidia/C-RADIOv3-B'
USE_SKIP_CONNECTIONS: False
USE_CBAM: False
PATCH_SIZE: 512
BATCH_SIZE: 16
DATA_WORKER_NUM: 8
TRAIN_EPOCHS: 150
BASE_LR: 0.001
FREEZE_ENCODER: False
ENCODER_LR_FACTOR: 0.1
ENCODER_LORA: False
FOCAL_LOSS: False
USE_SAM_DECODER: False

# TOPONET
# sample per patch
TOPO_SAMPLE_NUM: 512
TOPONET_VERSION: 'normal'

# Inference
INFER_BATCH_SIZE: 32
SAMPLE_MARGIN: 64
INFER_PATCHES_PER_EDGE: 16

# ======= keypoint ======
# Best threshold 0.10101009905338287, P=0.18603232502937317 R=0.25540080666542053 F1=0.215266153216362
# ======= road ======
# Best threshold 0.28282827138900757, P=0.48465853929519653 R=0.6257627606391907 F1=0.5462453961372375
# ======= topo ======
# Best threshold 0.46464645862579346, P=0.9764805436134338 R=0.9714608192443848 F1=0.9739642143249512

ITSC_THRESHOLD: 0.101
ROAD_THRESHOLD: 0.283
TOPO_THRESHOLD: 0.465
# pixels
ITSC_NMS_RADIUS: 8
ROAD_NMS_RADIUS: 16
NEIGHBOR_RADIUS: 64
MAX_NEIGHBOR_QUERIES: 16
