DATASET: 'cityscale'

# IN1k + MAE only
NO_SAM: False

BACKBONE: 'dinov3_convnext'
BACKBONE_NAME: 'facebook/dinov3-convnext-tiny-pretrain-lvd1689m'
USE_SKIP_CONNECTIONS: False
USE_CBAM: False
PATCH_SIZE: 512
BATCH_SIZE: 16
DATA_WORKER_NUM: 8
TRAIN_EPOCHS: 150
BASE_LR: 0.001
FREEZE_ENCODER: False
ENCODER_LR_FACTOR: 0.1
ENCODER_LORA: False
FOCAL_LOSS: False
USE_SAM_DECODER: False

# TOPONET
# sample per patch
TOPO_SAMPLE_NUM: 512
TOPONET_VERSION: 'normal'

# Inference
INFER_BATCH_SIZE: 32
SAMPLE_MARGIN: 64
INFER_PATCHES_PER_EDGE: 16

# ======= keypoint ======
# Best threshold 0.1818181872367859, P=0.36279287934303284 R=0.3098108470439911 F1=0.3342151343822479
# ======= road ======
# Best threshold 0.35353535413742065, P=0.6176242828369141 R=0.6944236159324646 F1=0.653776228427887
# ======= topo ======
# Best threshold 0.46464645862579346, P=0.9719069004058838 R=0.9657956957817078 F1=0.9688416123390198

ITSC_THRESHOLD: 0.1818
ROAD_THRESHOLD: 0.3535
TOPO_THRESHOLD: 0.4646
# pixels
ITSC_NMS_RADIUS: 8
ROAD_NMS_RADIUS: 16
NEIGHBOR_RADIUS: 64
MAX_NEIGHBOR_QUERIES: 16