DATASET: 'cityscale'

# IN1k + MAE only
NO_SAM: False

SAM_VERSION: 'radio'
BACKBONE: 'radio'
BACKBONE_NAME: 'nvidia/C-RADIOv3-B'
PATCH_SIZE: 512
BATCH_SIZE: 32
DATA_WORKER_NUM: 8
TRAIN_EPOCHS: 250
BASE_LR: 0.002
FREEZE_ENCODER: False
ENCODER_LR_FACTOR: 0.1
ENCODER_LORA: False
FOCAL_LOSS: False
USE_SAM_DECODER: False

# TOPONET
# sample per patch
TOPO_SAMPLE_NUM: 512
TOPONET_VERSION: 'normal'

# Inference
INFER_BATCH_SIZE: 32
SAMPLE_MARGIN: 64
INFER_PATCHES_PER_EDGE: 16

# ======= keypoint ======
# Best threshold 0.21435546875, P=0.3941706418991089 R=0.3310633599758148 F1=0.3598712980747223
# ======= road ======
# Best threshold 0.374755859375, P=0.6630836129188538 R=0.7252761125564575 F1=0.6927868723869324
# ======= topo ======
# Best threshold 0.47802734375, P=0.9722522497177124 R=0.9683084487915039 F1=0.9702762961387634

ITSC_THRESHOLD: 0.2143
ROAD_THRESHOLD: 0.3747
TOPO_THRESHOLD: 0.4780
# pixels
ITSC_NMS_RADIUS: 8
ROAD_NMS_RADIUS: 16
NEIGHBOR_RADIUS: 64
MAX_NEIGHBOR_QUERIES: 16