DATASET: 'cityscale'

# IN1k + MAE only
NO_SAM: False

SAM_VERSION: 'sam2_hiera_b+'
SAM_CKPT_PATH: 'sam_ckpts/sam2.1_hiera_base_plus.pt'
USE_SKIP_CONNECTIONS: True
USE_CBAM: True
USE_HIGH_RES_TOPO: True
PATCH_SIZE: 512
BATCH_SIZE: 16
DATA_WORKER_NUM: 8
TRAIN_EPOCHS: 250
BASE_LR: 0.001
FREEZE_ENCODER: False
ENCODER_LR_FACTOR: 0.1
ENCODER_LORA: False
FOCAL_LOSS: False
USE_SAM_DECODER: False

# TOPONET
# sample per patch
TOPO_SAMPLE_NUM: 512
TOPONET_VERSION: 'normal'

# Inference
INFER_BATCH_SIZE: 32
SAMPLE_MARGIN: 64
INFER_PATCHES_PER_EDGE: 16

# ======= keypoint ======
# Best threshold 0.1978759765625, P=0.42246556282043457 R=0.39057663083076477 F1=0.40589573979377747
# ======= road ======
# Best threshold 0.38671875, P=0.6869490742683411 R=0.7402161955833435 F1=0.7125885486602783
# ======= topo ======
# Best threshold 0.37451171875, P=0.9730762243270874 R=0.9747814536094666 F1=0.9739280939102173

ITSC_THRESHOLD: 0.1979
ROAD_THRESHOLD: 0.3867
TOPO_THRESHOLD: 0.3745
# pixels
ITSC_NMS_RADIUS: 8
ROAD_NMS_RADIUS: 16
NEIGHBOR_RADIUS: 64
MAX_NEIGHBOR_QUERIES: 16