DATASET: 'cityscale'

# IN1k + MAE only
NO_SAM: False

BACKBONE: 'dinov3_convnext'
BACKBONE_NAME: 'facebook/dinov3-convnext-tiny-pretrain-lvd1689m'
PATCH_SIZE: 512
BATCH_SIZE: 32
DATA_WORKER_NUM: 8
TRAIN_EPOCHS: 250
BASE_LR: 0.002
FREEZE_ENCODER: False
ENCODER_LR_FACTOR: 0.1
ENCODER_LORA: False
FOCAL_LOSS: False
USE_SAM_DECODER: False

# TOPONET
# sample per patch
TOPO_SAMPLE_NUM: 512
TOPONET_VERSION: 'normal'

# Inference
INFER_BATCH_SIZE: 32
SAMPLE_MARGIN: 64
INFER_PATCHES_PER_EDGE: 16

# ======= keypoint ======
# Best threshold 0.191650390625, P=0.3651096522808075 R=0.31333568692207336 F1=0.33724716305732727
# ======= road ======
# Best threshold 0.358642578125, P=0.6250861883163452 R=0.7024680376052856 F1=0.661521852016449
# ======= topo ======
# Best threshold 0.402099609375, P=0.9683887958526611 R=0.968612015247345 F1=0.9685004353523254

ITSC_THRESHOLD: 0.1916
ROAD_THRESHOLD: 0.3586
TOPO_THRESHOLD: 0.4021
# pixels
ITSC_NMS_RADIUS: 8
ROAD_NMS_RADIUS: 16
NEIGHBOR_RADIUS: 64
MAX_NEIGHBOR_QUERIES: 16