DATASET: 'cityscale'

# IN1k + MAE only
NO_SAM: False

SAM_VERSION: 'sam2_hiera_b+'
SAM_CKPT_PATH: 'sam_ckpts/sam2.1_hiera_base_plus.pt'
PATCH_SIZE: 512
BATCH_SIZE: 32
DATA_WORKER_NUM: 8
TRAIN_EPOCHS: 250
BASE_LR: 0.002
FREEZE_ENCODER: False
ENCODER_LR_FACTOR: 0.1
ENCODER_LORA: False
FOCAL_LOSS: False
USE_SAM_DECODER: False

# TOPONET
# sample per patch
TOPO_SAMPLE_NUM: 512
TOPONET_VERSION: 'normal'

# Inference
INFER_BATCH_SIZE: 32
SAMPLE_MARGIN: 64
INFER_PATCHES_PER_EDGE: 16

# ======= keypoint ======
# Best threshold 0.2359619140625, P=0.43437862396240234 R=0.3836853504180908 F1=0.40746134519577026
# ======= road ======
# Best threshold 0.379150390625, P=0.6981678605079651 R=0.7536000609397888 F1=0.7248256802558899
# ======= topo ======
# Best threshold 0.43505859375, P=0.974816083908081 R=0.9728009700775146 F1=0.9738074541091919

ITSC_THRESHOLD: 0.235
ROAD_THRESHOLD: 0.379
TOPO_THRESHOLD: 0.435
# pixels
ITSC_NMS_RADIUS: 8
ROAD_NMS_RADIUS: 16
NEIGHBOR_RADIUS: 64
MAX_NEIGHBOR_QUERIES: 16