DATASET: 'globalscale_outdomain'

# IN1k + MAE only
NO_SAM: False

BACKBONE: 'dinov3_convnext'
BACKBONE_NAME: 'facebook/dinov3-convnext-tiny-pretrain-lvd1689m'
USE_SKIP_CONNECTIONS: False
USE_CBAM: False
PATCH_SIZE: 512
BATCH_SIZE: 16
DATA_WORKER_NUM: 8
TRAIN_EPOCHS: 150
BASE_LR: 0.001
FREEZE_ENCODER: False
ENCODER_LR_FACTOR: 0.1
ENCODER_LORA: False
FOCAL_LOSS: False
USE_SAM_DECODER: False

# TOPONET
# sample per patch
TOPO_SAMPLE_NUM: 512
TOPONET_VERSION: 'normal'

# Inference
INFER_BATCH_SIZE: 32
SAMPLE_MARGIN: 64
INFER_PATCHES_PER_EDGE: 16

# ======= keypoint ======
# Best threshold 0.09090909361839294, P=0.15001706779003143 R=0.21060968935489655 F1=0.1752229779958725
# ======= road ======
# Best threshold 0.2626262605190277, P=0.43040475249290466 R=0.6052730679512024 F1=0.5030761957168579
# ======= topo ======
# Best threshold 0.4444444477558136, P=0.97452712059021 R=0.9707310795783997 F1=0.9726253747940063

ITSC_THRESHOLD: 0.091
ROAD_THRESHOLD: 0.263
TOPO_THRESHOLD: 0.444
# pixels
ITSC_NMS_RADIUS: 8
ROAD_NMS_RADIUS: 16
NEIGHBOR_RADIUS: 64
MAX_NEIGHBOR_QUERIES: 16
