DATASET: "cityscale"
MODEL_TYPE: "gte"
SAM_VERSION: "sam2_hiera_b+"
SAM_CKPT_PATH: "sam_ckpts/sam2.1_hiera_base_plus.pt"
NO_VFM: False
BACKBONE: "sam2"
PATCH_SIZE: 512
BATCH_SIZE: 16
DATA_WORKER_NUM: 8
TRAIN_EPOCHS: 250
BASE_LR: 0.001
FREEZE_ENCODER: False
ENCODER_LR_FACTOR: 0.1
ENCODER_LORA: False
GTE_DECODER_VERSION: "v1"
INFER_BATCH_SIZE: 32
SAMPLE_MARGIN: 64
INFER_PATCHES_PER_EDGE: 16
