DATASET: 'globalscale_outdomain'

# IN1k + MAE only
NO_SAM: False

BACKBONE: 'resnet'
USE_SKIP_CONNECTIONS: False
USE_CBAM: False
PATCH_SIZE: 512
BATCH_SIZE: 16
DATA_WORKER_NUM: 8
TRAIN_EPOCHS: 150
BASE_LR: 0.001
FREEZE_ENCODER: False
ENCODER_LR_FACTOR: 0.1
ENCODER_LORA: False
FOCAL_LOSS: False
USE_SAM_DECODER: False

# TOPONET
# sample per patch
TOPO_SAMPLE_NUM: 512
TOPONET_VERSION: 'normal'

# Inference
INFER_BATCH_SIZE: 32
SAMPLE_MARGIN: 64
INFER_PATCHES_PER_EDGE: 16

# Thresholds
ITSC_THRESHOLD: 0.2
ROAD_THRESHOLD: 0.35
TOPO_THRESHOLD: 0.45
# pixels
ITSC_NMS_RADIUS: 8
ROAD_NMS_RADIUS: 16
NEIGHBOR_RADIUS: 64
MAX_NEIGHBOR_QUERIES: 16
